server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/InterView
    username: root
    password: Nhuy1502
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
       registration:
         api-client-oidc:
           provider: spring
           client-id: api-client
           client-Secret: secret
           authorization-grant-type: authorization_code
           redirectUri: "http://127.0.0.1:8080/login/oauth2/code/{registrationID}"
           scope: openid
           client-name: api-client-oidc
        api-client-authorization-code:
          provider: spring
          client-id: api-client
          client-Secret: secret
          authorization-grant-type: authorization_code
          redirectUri: "http://127.0.0.1:8080/authorization"
            scope: api.read
            client-name: api-client-authorization-oidc
        provider:
          spring:
            issuer-uri: http://auth-server:9000